\set ON_ERROR_STOP on
\pset pager off

SET lock_timeout = '2s';
SET statement_timeout = '15min';
SET idle_in_transaction_session_timeout = '60s';

\echo Rebuilding disposable demo schema for expand-contract patterns
DROP SCHEMA IF EXISTS dbre_migration_demo CASCADE;
CREATE SCHEMA dbre_migration_demo;

CREATE TABLE dbre_migration_demo.orders (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb
) WITH (fillfactor = 90);

INSERT INTO dbre_migration_demo.orders (customer_id, status, created_at, payload)
SELECT
  100000 + gs,
  CASE
    WHEN gs % 7 = 0 THEN 'processing'
    WHEN gs % 11 = 0 THEN 'failed'
    ELSE 'completed'
  END,
  now() - make_interval(hours => gs % 72),
  jsonb_build_object('batch', gs % 50, 'source', 'demo')
FROM generate_series(1, 10000) AS gs;

\echo Expand: add nullable column without rewrite
ALTER TABLE dbre_migration_demo.orders
  ADD COLUMN external_reference text;

\echo Backfill in throttled batches
DO $$
DECLARE
  rows_updated integer;
BEGIN
  LOOP
    UPDATE dbre_migration_demo.orders AS t
    SET external_reference = md5(t.order_id::text)
    WHERE t.ctid IN (
      SELECT ctid
      FROM dbre_migration_demo.orders
      WHERE external_reference IS NULL
      LIMIT 500
    );

    GET DIAGNOSTICS rows_updated = ROW_COUNT;
    EXIT WHEN rows_updated = 0;
    PERFORM pg_sleep(0.02);
  END LOOP;
END
$$;

\echo Add the new access path concurrently
CREATE INDEX CONCURRENTLY orders_external_reference_idx
  ON dbre_migration_demo.orders (external_reference);

\echo Add constraints with NOT VALID first
ALTER TABLE dbre_migration_demo.orders
  ADD CONSTRAINT orders_external_reference_format_ck
  CHECK (external_reference ~ '^[0-9a-f]{32}$')
  NOT VALID;

ALTER TABLE dbre_migration_demo.orders
  VALIDATE CONSTRAINT orders_external_reference_format_ck;

\echo Contract: enforce not-null only after data and checks are in place
ALTER TABLE dbre_migration_demo.orders
  ALTER COLUMN external_reference SET NOT NULL;

\echo Final posture
SELECT
  c.relname,
  c.reloptions,
  pg_size_pretty(pg_table_size(c.oid)) AS table_size,
  pg_size_pretty(pg_indexes_size(c.oid)) AS indexes_size
FROM pg_class AS c
JOIN pg_namespace AS n
  ON n.oid = c.relnamespace
WHERE n.nspname = 'dbre_migration_demo'
  AND c.relname = 'orders';

SELECT
  count(*) AS rows_loaded,
  min(external_reference) IS NOT NULL AS has_backfill,
  count(*) FILTER (WHERE external_reference IS NULL) AS null_references
FROM dbre_migration_demo.orders;
